# Generated by Django 5.0.6 on 2024-06-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("surname", models.CharField(max_length=256)),
                ("birthday", models.DateField()),
                ("picture", models.ImageField(blank=True, upload_to="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("tags", models.ManyToManyField(to="common.tag")),
            ],
        ),
    ]
