# Generated by Django 5.0.6 on 2024-06-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="tags",
            field=models.ManyToManyField(blank=True, to="common.tag"),
        ),
    ]
