# Generated by Django 5.0.6 on 2024-06-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_alter_profile_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="body",
            field=models.TextField(blank=True, max_length=2048),
        ),
    ]
