# Generated by Django 5.0.3 on 2024-03-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_alter_profile_picture"),
        ("reports", "0005_report_is_plead_guilty_report_is_processed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="tags",
            field=models.ManyToManyField(to="reports.tag"),
        ),
    ]
