# Generated by Django 5.0.3 on 2024-05-10 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_profile_tags"),
        ("reports", "0006_charge"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="charges",
            field=models.ManyToManyField(to="reports.charge"),
        ),
    ]
