# Generated by Django 5.1 on 2024-09-01 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="Legislation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("description", models.TextField(max_length=1024)),
                ("time", models.IntegerField()),
                ("fine", models.IntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("info", "Misdemeanor"),
                            ("warning", "Felony"),
                            ("danger", "Critical"),
                        ],
                        default="info",
                        max_length=32,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="legislations.category",
                    ),
                ),
            ],
        ),
    ]
