# Generated by Django 5.1 on 2024-08-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legislations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="legislation",
            name="type",
            field=models.CharField(
                choices=[
                    ("info", "Misdemeanor"),
                    ("warning", "Felony"),
                    ("danger", "Critical"),
                ],
                default="info",
                max_length=32,
            ),
        ),
    ]
