# Generated by Django 5.0.7 on 2024-08-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_tag_icon"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("body", models.CharField(max_length=1024)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
