# Generated by Django 5.0.7 on 2024-08-03 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[("info", "Info"), ("warning", "Warning"), ("error", "Error")],
                default="Info",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="body",
            field=models.TextField(max_length=1024),
        ),
    ]
