# Generated by Django 5.1 on 2024-08-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_notification_type_alter_notification_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[("info", "Info"), ("warning", "Warning"), ("danger", "Error")],
                default="info",
                max_length=32,
            ),
        ),
    ]
