# Generated by Django 5.1.2 on 2024-10-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_badge_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="rank",
            name="icon",
            field=models.ImageField(blank=True, null=True, upload_to="accounts/rank"),
        ),
    ]
