# Generated by Django 5.1.3 on 2024-11-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalreport",
            name="is_plead_guilty",
        ),
        migrations.RemoveField(
            model_name="historicalreport",
            name="is_processed",
        ),
        migrations.RemoveField(
            model_name="historicalreport",
            name="is_warrant",
        ),
        migrations.RemoveField(
            model_name="report",
            name="is_plead_guilty",
        ),
        migrations.RemoveField(
            model_name="report",
            name="is_processed",
        ),
        migrations.RemoveField(
            model_name="report",
            name="is_warrant",
        ),
        migrations.AddField(
            model_name="suspect",
            name="is_plead_guilty",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="suspect",
            name="is_processed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="suspect",
            name="is_warrant",
            field=models.BooleanField(default=False),
        ),
    ]
