# Generated by Django 5.0.6 on 2024-06-07 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportsuspect",
            name="suspect",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="profiles.profile"
            ),
        ),
    ]
