# Generated by Django 5.0.6 on 2024-06-07 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_alter_reportsuspect_suspect"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportsuspect",
            name="charges",
            field=models.ManyToManyField(blank=True, to="reports.charge"),
        ),
        migrations.AlterField(
            model_name="reportsuspect",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="suspects",
                to="reports.report",
            ),
        ),
    ]
