# Generated by Django 5.0.6 on 2024-06-09 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
        ("reports", "0003_alter_reportsuspect_charges_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Suspect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("charges", models.ManyToManyField(blank=True, to="reports.charge")),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.profile",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suspects",
                        to="reports.report",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ReportSuspect",
        ),
    ]
