# Generated by Django 5.0.3 on 2024-03-17 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0003_evidence_report_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="created_at",
        ),
    ]
