# Generated by Django 5.0.3 on 2024-03-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0004_remove_tag_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="is_plead_guilty",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="report",
            name="is_processed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="report",
            name="is_warrant",
            field=models.BooleanField(default=False),
        ),
    ]
