# Generated by Django 5.0.6 on 2024-06-09 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0004_suspect_delete_reportsuspect"),
    ]

    operations = [
        migrations.AddField(
            model_name="suspect",
            name="created_at",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
