# Generated by Django 5.0.6 on 2024-06-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0005_suspect_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suspect",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
