# Generated by Django 5.0.3 on 2024-05-10 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_profile_charges"),
        ("reports", "0006_charge"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="suspect",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="profiles.profile",
            ),
        ),
    ]
