# Generated by Django 5.0.6 on 2024-05-10 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0008_alter_report_suspect"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="suspect",
        ),
    ]
