# Generated by Django 5.0.6 on 2024-06-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0009_remove_report_suspect"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportSuspect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("suspect", models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name="report",
            name="suspects",
            field=models.ManyToManyField(to="reports.reportsuspect"),
        ),
    ]
