# Generated by Django 5.0.6 on 2024-06-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0009_historicalreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalreport",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="report",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
