# Generated by Django 5.0.7 on 2024-08-03 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0011_legislation_remove_charge_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="legislation",
            name="fine",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="legislation",
            name="time",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="charge",
            name="legislation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="reports.legislation"
            ),
        ),
        migrations.AlterField(
            model_name="charge",
            name="suspect",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="charges",
                to="reports.suspect",
            ),
        ),
    ]
