# Generated by Django 5.1 on 2024-08-08 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legislations", "0001_initial"),
        ("profiles", "0004_historicalprofile"),
        ("reports", "0013_alter_suspect_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charge",
            name="legislation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="legislations.legislation",
            ),
        ),
        migrations.AlterField(
            model_name="suspect",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="suspect_appearances",
                to="profiles.profile",
            ),
        ),
        migrations.DeleteModel(
            name="Legislation",
        ),
    ]
